const SUPABASE_URL='https://ymiqcnzulxbshjrnaujv.supabase.co';
const SUPABASE_KEY='sb_publishable_-rbhLGxEgLXlfMZ64W7ypw_xyy3aLjR';
const headers=()=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${session?.access_token||SUPABASE_KEY}`});
let session=null, posts=[];
const $=s=>document.querySelector(s);
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmt(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(d);}
function statusLabel(v){return({review:'Publicado',draft:'Rascunho',archived:'Arquivado'})[v]||v||'Sem status';}
async function authLogin(email,password){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'Login inválido');return d;}
async function checkAdmin(){const r=await fetch(`${SUPABASE_URL}/rest/v1/admin_users?select=email&limit=1`,{headers:headers()});if(!r.ok)return false;const d=await r.json();return d.length>0;}
function renderStats(s){const cards=[['Visitas ao site',s.visits||0],['Visualizações de posts',s.article_views||0],['Curtidas',s.likes||0],['Compartilhamentos',s.shares||0],['Posts publicados',s.review_posts||0],['Rascunhos',s.draft_posts||0],['Arquivados',s.archived_posts||0],['Posts no banco',s.total_posts||0],['Posts sem data',s.null_date_posts||0],['Comentários',s.comments||0]];$('#stats').innerHTML=cards.map(x=>`<div class="stat"><span>${x[0]}</span><strong>${Number(x[1]).toLocaleString('pt-BR')}</strong></div>`).join('');}
async function loadStats(){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/admin_dashboard_stats`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:'{}'});if(!r.ok){let msg='Não foi possível carregar as estatísticas.';try{const d=await r.json();msg=d.message||d.hint||msg}catch(e){}throw new Error(msg)}const s=await r.json()||{};renderStats(s);posts=Array.isArray(s.top_posts)?s.top_posts:[];renderPosts();$('#dashboard-updated').textContent=`Atualizado em ${fmt(new Date())}`;}
function renderPosts(){const q=($('#post-search').value||'').trim().toLowerCase();const filter=$('#status-filter').value;const list=posts.filter(p=>{const title=(p.title||'').toLowerCase();return(!q||title.includes(q))&&(filter==='all'||p.status===filter)});$('#post-count').textContent=`Mostrando ${list.length} de ${posts.length} matérias carregadas`;$('#posts').innerHTML=list.length?list.map(p=>`<div class="post-row"><div><div class="post-topline"><span class="status status-${esc(p.status||'unknown')}">${esc(statusLabel(p.status))}</span><span>${fmt(p.published_at||p.created_at)}</span></div><h3>${esc(p.title)}</h3><div class="post-meta">${p.views||0} visualizações · ${p.likes||0} curtidas · ${p.shares||0} compartilhamentos · ${p.comments||0} comentários${!p.published_at?' · sem data de publicação':''}</div></div><div class="post-actions"><button class="danger" data-delete="${esc(p.id)}">Apagar</button></div></div>`).join(''):'<div class="empty">Nenhum post encontrado com esses filtros.</div>';document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deletePost(b.dataset.delete));}
async function deletePost(id){const p=posts.find(x=>x.id===id);if(!p)return;if(!confirm(`Apagar esta matéria?\n\n${p.title}\n\nEssa ação remove a matéria do site.`))return;const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/admin_delete_article`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({p_article_id:id})});if(!r.ok){alert('Não foi possível apagar a matéria.');return;}await loadStats();}
async function boot(){const raw=localStorage.getItem('techcheck_admin_session');if(raw){try{session=JSON.parse(raw);if(await checkAdmin())return showDashboard();}catch(e){}localStorage.removeItem('techcheck_admin_session');}$('#login-view').hidden=false;$('#dashboard-view').hidden=true;}
function showDashboard(){$('#login-view').hidden=true;$('#dashboard-view').hidden=false;loadStats().catch(e=>{alert(e.message);logout();});}
function logout(){session=null;localStorage.removeItem('techcheck_admin_session');$('#dashboard-view').hidden=true;$('#login-view').hidden=false;}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';try{session=await authLogin($('#email').value.trim(),$('#password').value);localStorage.setItem('techcheck_admin_session',JSON.stringify(session));if(!await checkAdmin())throw new Error('Este usuário não está autorizado como administrador.');showDashboard();}catch(err){session=null;localStorage.removeItem('techcheck_admin_session');$('#login-error').textContent=err.message;}});
$('#logout').onclick=logout;$('#refresh').onclick=()=>loadStats().catch(e=>alert(e.message));$('#post-search').addEventListener('input',renderPosts);$('#status-filter').addEventListener('change',renderPosts);boot();