const CATEGORY_META={
 'inteligencia-artificial':{name:'Inteligência Artificial',description:'Notícias, lançamentos, pesquisas e tendências de inteligência artificial, modelos de IA, ferramentas e aplicações.'},
 'games':{name:'Games',description:'Notícias sobre games, consoles, PC, lançamentos, estúdios, atualizações e novidades do mundo dos jogos.'},
 'filmes-series-animacoes':{name:'Filmes, Séries e Animações',description:'Notícias sobre filmes, séries, animações, streaming, cinema, produções e tecnologia do entretenimento.'},
 'smartphones-gadgets':{name:'Smartphones e Gadgets',description:'Notícias sobre smartphones, wearables, acessórios, dispositivos conectados e novos gadgets.'},
 'computadores':{name:'Computadores',description:'Notícias sobre computadores, hardware, notebooks, processadores, placas de vídeo, sistemas e periféricos.'},
 'ciencia-espaco':{name:'Ciência e Espaço',description:'Descobertas científicas, astronomia, exploração espacial, pesquisas e novidades que ampliam o conhecimento.'},
 'seguranca':{name:'Segurança',description:'Notícias sobre segurança digital, golpes, vulnerabilidades, privacidade, malware e proteção de dados.'},
 'internet':{name:'Internet',description:'Notícias sobre internet, redes sociais, plataformas, serviços online, conectividade e cultura digital.'},
 'empresas':{name:'Empresas',description:'Notícias sobre empresas de tecnologia, negócios, produtos, investimentos, mercado e movimentos da indústria.'}
};
const key=location.pathname.split('/').filter(Boolean).pop()||'inteligencia-artificial';const meta=CATEGORY_META[key]||CATEGORY_META['inteligencia-artificial'];
const SUP='https://ymiqcnzulxbshjrnaujv.supabase.co', KEY='sb_publishable_-rbhLGxEgLXlfMZ64W7ypw_xyy3aLjR';const headers={apikey:KEY,Authorization:`Bearer ${KEY}`};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const slugify=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function render(items){document.title=`${meta.name} — Tech Check`;document.querySelector('#page-title').textContent=meta.name;document.querySelector('#page-description').textContent=meta.description;document.querySelector('#page-count').textContent=`${items.length} matérias`;document.querySelector('#category-grid').innerHTML=items.map(a=>`<article class="news-card"><div class="card-image">${a.image_url?`<img class="real-image" src="${esc(a.image_url)}" alt="" loading="lazy">`:''}</div><div class="card-body"><div class="card-meta"><span>${esc(meta.name)}</span><span>${a.published_at?new Date(a.published_at).toLocaleDateString('pt-BR'):''}</span></div><h3>${esc(a.title)}</h3><p>${esc(a.summary||'')}</p><a class="read-button" href="../noticias/${encodeURIComponent(a.slug||a.id)}/">Ler matéria</a></div></article>`).join('')}
async function load(){try{const cats=await fetch(`${SUP}/rest/v1/categories?name=eq.${encodeURIComponent(meta.name)}&select=id,name`,{headers}).then(r=>r.json());if(!cats[0])return render([]);const links=await fetch(`${SUP}/rest/v1/article_categories?category_id=eq.${cats[0].id}&select=article_id`,{headers}).then(r=>r.json());const ids=links.map(x=>x.article_id);if(!ids.length)return render([]);const filter=ids.map(id=>`id.eq.${id}`).join(',');const articles=await fetch(`${SUP}/rest/v1/articles?or=(${filter})&status=eq.review&select=id,title,slug,summary,image_url,published_at&order=published_at.desc.nullslast&limit=1000`,{headers}).then(r=>r.json());render(articles)}catch(e){console.error(e)}}load();