const EVERGREEN_URL='https://ymiqcnzulxbshjrnaujv.supabase.co';
const EVERGREEN_KEY='sb_publishable_-rbhLGxEgLXlfMZ64W7ypw_xyy3aLjR';
const evergreenHeaders={apikey:EVERGREEN_KEY,Authorization:`Bearer ${EVERGREEN_KEY}`};
let curiosityItems=[],historyItems=[],curiosityLimit=6,historyLimit=8;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(item,type){return `<article class="evergreen-card ${type==='history'?'history-card':''}"><div class="evergreen-card-top"><span>${type==='history'?'HISTÓRIA':'CURIOSIDADE'}</span></div><h3>${esc(item.title)}</h3><p class="evergreen-summary">${esc(item.summary||'')}</p><button type="button" class="evergreen-read" data-evergreen-id="${item.id}">Ler conteúdo</button></article>`}
function renderEvergreen(){const cg=document.querySelector('#curiosity-grid'),hg=document.querySelector('#history-timeline');if(cg)cg.innerHTML=curiosityItems.slice(0,curiosityLimit).map(x=>card(x,'curiosity')).join('');if(hg)hg.innerHTML=historyItems.slice(0,historyLimit).map(x=>card(x,'history')).join('');document.querySelector('#curiosity-count').textContent=`${curiosityItems.length} curiosidades`;document.querySelector('#history-count').textContent=`${historyItems.length} marcos`;const cb=document.querySelector('#curiosity-more'),hb=document.querySelector('#history-more');if(cb)cb.hidden=curiosityLimit>=curiosityItems.length;if(hb)hb.hidden=historyLimit>=historyItems.length;document.querySelectorAll('[data-evergreen-id]').forEach(b=>b.addEventListener('click',()=>openEvergreen(Number(b.dataset.evergreenId))));}
function openEvergreen(id){const item=[...curiosityItems,...historyItems].find(x=>x.id===id);if(!item)return;const modal=document.querySelector('#article-modal'),box=document.querySelector('#modal-content');const body=String(item.content||'').split(/\n+/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('');box.innerHTML=`${item.image_url?`<img class="modal-hero-image" src="${esc(item.image_url)}" alt="${esc(item.title)}">`:''}<p class="eyebrow">${item.content_type==='history'?'HISTÓRIA DA TECNOLOGIA':'CURIOSIDADE TECNOLÓGICA'}</p><h2 id="modal-title">${esc(item.title)}</h2><p class="modal-summary">${esc(item.summary||'')}</p><div class="article-body">${body}</div>`;modal.hidden=false;document.body.classList.add('modal-open');window.history.pushState({evergreen:true},'',`#${item.content_type==='history'?'historia':'curiosidades'}/${item.id}`);}
async function loadEvergreen(){try{const r=await fetch(`${EVERGREEN_URL}/rest/v1/tech_evergreen_content?active=eq.true&select=id,content_type,title,summary,content,image_url,sort_order&order=content_type.asc,sort_order.asc`,{headers:evergreenHeaders});if(!r.ok)throw new Error(`evergreen ${r.status}`);const data=await r.json();curiosityItems=data.filter(x=>x.content_type==='curiosity');historyItems=data.filter(x=>x.content_type==='history');renderEvergreen();}catch(e){console.error('Evergreen:',e);document.querySelector('#curiosity-count').textContent='Conteúdo indisponível';document.querySelector('#history-count').textContent='Conteúdo indisponível';}}
document.querySelector('#curiosity-more')?.addEventListener('click',()=>{curiosityLimit+=6;renderEvergreen();});document.querySelector('#history-more')?.addEventListener('click',()=>{historyLimit+=8;renderEvergreen();});loadEvergreen();
