const EVERGREEN_URL='https://ymiqcnzulxbshjrnaujv.supabase.co';
const EVERGREEN_KEY='sb_publishable_-rbhLGxEgLXlfMZ64W7ypw_xyy3aLjR';
const evergreenHeaders={apikey:EVERGREEN_KEY,Authorization:`Bearer ${EVERGREEN_KEY}`};
let curiosityItems=[],historyItems=[],tutorialItems=[],curiosityLimit=10,historyLimit=8,tutorialLimit=10;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cleanEvergreenText(v=''){return String(v??'').replace(/\\r\\n/g,'\n').replace(/\\n/g,'\n').replace(/\\r/g,'\n').replace(/\r\n/g,'\n').trim()}
function card(item,type){const label=type==='history'?'HISTÓRIA':type==='tutorial'?'TUTORIAL':'LISTA';return `<article class="evergreen-card ${type==='history'?'history-card':''} ${type==='tutorial'?'tutorial-card':''}">${item.image_url?`<img class="evergreen-card-image" src="${esc(item.image_url)}" alt="${esc(item.title)}" loading="lazy" decoding="async">`:''}<div class="evergreen-card-top"><span>${label}</span></div><h3>${esc(item.title)}</h3><p class="evergreen-summary">${esc(item.summary||'')}</p><button type="button" class="evergreen-read" data-evergreen-type="${type}" data-evergreen-id="${item.id}">Ler conteúdo</button></article>`}
function renderEvergreen(){const cg=document.querySelector('#curiosity-grid'),hg=document.querySelector('#history-timeline'),tg=document.querySelector('#tutorial-grid');if(cg)cg.innerHTML=curiosityItems.slice(0,curiosityLimit).map(x=>card(x,'curiosity')).join('');if(hg)hg.innerHTML=historyItems.slice(0,historyLimit).map(x=>card(x,'history')).join('');if(tg)tg.innerHTML=tutorialItems.slice(0,tutorialLimit).map(x=>card(x,'tutorial')).join('');const cb=document.querySelector('#curiosity-more'),hb=document.querySelector('#history-more'),tb=document.querySelector('#tutorial-more');if(cb)cb.hidden=curiosityLimit>=curiosityItems.length;if(hb)hb.hidden=historyLimit>=historyItems.length;if(tb)tb.hidden=tutorialLimit>=tutorialItems.length;document.querySelectorAll('[data-evergreen-id]').forEach(b=>b.addEventListener('click',()=>openEvergreen(Number(b.dataset.evergreenId),b.dataset.evergreenType)));}
function evergreenBody(item){const lines=cleanEvergreenText(item.content).split(/\n+/).map(x=>x.trim()).filter(Boolean).filter((line,i)=>!(i===0&&/^TL;DR\s*:/i.test(line)));if(item.content_type==='curiosity'){return `<div class="article-list">${lines.map(line=>{const m=line.match(/^(\d+)\.\s*(.*)$/);return m?`<div class="article-list-item"><h3>${m[1]}. ${esc(m[2].split('. ')[0]||'')}</h3><p>${esc(m[2])}</p></div>`:`<p>${esc(line)}</p>`}).join('')}</div>`}return lines.map(p=>`<p>${esc(p)}</p>`).join('')}
function openEvergreen(id,type){const item=[...curiosityItems,...historyItems,...tutorialItems].find(x=>x.id===id&&((type==='history'&&x.content_type==='history')||(type==='tutorial'&&x.content_type==='tutorial')||(type==='curiosity'&&x.content_type==='curiosity')));if(!item)return;const modal=document.querySelector('#article-modal'),box=document.querySelector('#modal-content');const label=item.content_type==='history'?'HISTÓRIA DA TECNOLOGIA':item.content_type==='tutorial'?'TUTORIAL':'CURIOSIDADE EM LISTA';box.innerHTML=`${item.image_url?`<img class="modal-hero-image" src="${esc(item.image_url)}" alt="${esc(item.title)}" loading="eager" decoding="async">`:''}<p class="eyebrow">${label}</p><h2 id="modal-title">${esc(item.title)}</h2><div class="article-tldr"><strong>TL;DR</strong><p>${esc(item.summary||'')}</p></div><div class="article-body">${evergreenBody(item)}</div>`;modal.hidden=false;document.body.classList.add('modal-open');window.history.pushState({evergreen:true},'',`#${item.content_type==='history'?'historia':item.content_type==='tutorial'?'tutoriais':'curiosidades'}/${item.id}`);}
async function loadEvergreen(){try{const r=await fetch(`${EVERGREEN_URL}/rest/v1/tech_evergreen_content?active=eq.true&select=id,content_type,title,summary,content,image_url,sort_order&order=content_type.asc,sort_order.asc`,{headers:evergreenHeaders});if(!r.ok)throw new Error(`evergreen ${r.status}`);const data=await r.json();curiosityItems=data.filter(x=>x.content_type==='curiosity');historyItems=data.filter(x=>x.content_type==='history');tutorialItems=data.filter(x=>x.content_type==='tutorial');renderEvergreen();}catch(e){console.error('Evergreen:',e);}}
document.querySelector('#curiosity-more')?.addEventListener('click',()=>{curiosityLimit+=6;renderEvergreen();});document.querySelector('#history-more')?.addEventListener('click',()=>{historyLimit+=8;renderEvergreen();});document.querySelector('#tutorial-more')?.addEventListener('click',()=>{tutorialLimit+=6;renderEvergreen();});loadEvergreen();
