const RELATED_LIMIT=5;
function relatedSlugFromPath(){const m=location.pathname.match(/\/noticias\/([^/]+)/);return m?decodeURIComponent(m[1]):null;}
function relatedCard(a){return `<a class="related-card" href="${articlePath(a)}" data-related-id="${escapeHtml(a.id)}"><div class="related-card-title">${escapeHtml(a.title||'Sem título')}</div><span>${escapeHtml(a.category||'Tecnologia')} · ${formatDate(a.published_at||a.created_at)}</span></a>`;}
function openRelatedArticle(a){if(!a)return;history.pushState({techCheckPost:true,articleId:a.id},'',articlePath(a));openArticle(a);}
function relatedTokens(text=''){return String(text).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/[^a-z0-9]+/).filter(t=>t.length>=4);}
async function loadRelatedForCurrentArticle(){const slug=relatedSlugFromPath();if(!slug||!modalContent||modal.hidden)return;try{const currentResponse=await fetch(`${SUPABASE_URL}/rest/v1/articles?slug=eq.${encodeURIComponent(slug)}&select=id,title,summary,content,published_at,created_at`,{headers:apiHeaders});if(!currentResponse.ok)return;const currentRows=await currentResponse.json();const current=currentRows[0];if(!current)return;const listResponse=await fetch(`${SUPABASE_URL}/rest/v1/articles?status=eq.review&select=id,slug,title,summary,content,published_at,created_at&order=published_at.desc.nullslast,created_at.desc&limit=100`,{headers:apiHeaders});if(!listResponse.ok)return;const articles=await listResponse.json();const tokens=[...new Set(relatedTokens(`${current.title} ${current.summary||''}`))];const scored=articles.filter(a=>a.id!==current.id).map(a=>{const articleTokens=new Set(relatedTokens(`${a.title||''} ${a.summary||''}`));let score=0;for(const t of tokens){if(articleTokens.has(t))score+=t.length>=7?4:2;}return {...a,score};}).filter(a=>a.score>0).sort((a,b)=>b.score-a.score).slice(0,RELATED_LIMIT);if(!scored.length){const fallback=articles.filter(a=>a.id!==current.id).slice(0,RELATED_LIMIT);if(!fallback.length)return;scored.push(...fallback);}
// Um único bloco "LEIA TAMBÉM", sempre no final do texto, em carrossel.
const articleBody=modalContent.querySelector('.article-body');
if(!articleBody)return;
modalContent.querySelectorAll('.read-also,.related-section').forEach(el=>el.remove());
const readAlso=document.createElement('section');readAlso.className='read-also';readAlso.innerHTML=`<p class="eyebrow">LEIA TAMBÉM</p><div class="read-also-list">${scored.slice(0,5).map(relatedCard).join('')}</div>`;articleBody.appendChild(readAlso);
const related=document.createElement('section');related.className='related-section';related.innerHTML=`<p class="eyebrow">CONTINUE LENDO</p><h3>Matérias relacionadas</h3><div class="related-grid">${scored.map(relatedCard).join('')}</div>`;const source=modalContent.querySelector('.source-box');(source||modalContent).after(related);
readAlso.querySelectorAll('.related-card').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const a=articles.find(x=>x.id===link.dataset.relatedId);openRelatedArticle(a);}));related.querySelectorAll('.related-card').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const a=articles.find(x=>x.id===link.dataset.relatedId);openRelatedArticle(a);}));}catch(error){console.warn('Relacionados:',error);}}
const relatedObserver=new MutationObserver(()=>{if(!modal.hidden&&!modalContent.querySelector('.related-section'))setTimeout(loadRelatedForCurrentArticle,50);});
if(modalContent)relatedObserver.observe(modalContent,{childList:true,subtree:true});