import { writeFile } from 'node:fs/promises';
import { getDraftArticles, updateArticle, getCategoryByName, attachCategory, getPublishedArticles } from './supabase.mjs';
const GEMINI_API_KEY=process.env.GEMINI_API_KEY;const GEMINI_MODEL=process.env.GEMINI_MODEL||'gemini-3.5-flash-lite';const GEMINI_FALLBACK_MODEL=process.env.GEMINI_FALLBACK_MODEL||'gemini-3.1-flash-lite';if(!GEMINI_API_KEY)throw new Error('GEMINI_API_KEY não está configurada nos secrets do GitHub.');
const categories=['Inteligência Artificial','Smartphones','Computadores','Games','Filmes, Séries e Animações','Segurança','Ciência','Internet','Empresas'];const aliases=new Map([['IA','Inteligência Artificial'],['Artificial Intelligence','Inteligência Artificial'],['Apps','Internet'],['Aplicativos','Internet'],['Web','Internet'],['Filmes','Filmes, Séries e Animações'],['Séries','Filmes, Séries e Animações'],['Cinema','Filmes, Séries e Animações'],['Hardware','Computadores'],['PC','Computadores'],['Mobile','Smartphones'],['Celulares','Smartphones'],['Privacidade','Segurança'],['Cibersegurança','Segurança'],['Cybersecurity','Segurança'],['Negócios','Empresas'],['Business','Empresas']]);
const responseSchema={type:'OBJECT',properties:{title:{type:'STRING'},summary:{type:'STRING'},content:{type:'STRING'},why_it_matters:{type:'STRING'},future_outlook:{type:'STRING'},category:{type:'STRING'},verification_level:{type:'STRING',enum:['single_source','official_source']}},required:['title','summary','content','why_it_matters','future_outlook','category','verification_level']};
function parseJsonText(t){const s=(t||'').trim();if(!s)throw Error('Gemini retornou uma resposta vazia.');try{return JSON.parse(s)}catch{}const f=s.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();try{return JSON.parse(f)}catch{}const a=f.indexOf('{'),b=f.lastIndexOf('}');if(a>=0&&b>a)try{return JSON.parse(f.slice(a,b+1))}catch{}throw Error(`Resposta do Gemini não é JSON válido: ${s.slice(0,500)}`)}
function decode(v=''){return v.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>')}
function htmlText(h=''){return decode(h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<svg[\s\S]*?<\/svg>/gi,' ').replace(/<br\s*\/?>/gi,'\n').replace(/<\/(?:p|div|section|article|main|li|h[1-6]|blockquote)>/gi,'\n').replace(/<[^>]+>/g,' ')).split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean).join('\n')}
async function fetchOriginalArticle(url){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 Tech-Check/1.0','Accept':'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(`fonte ${r.status}`);const h=await r.text();for(const m of h.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const raw=JSON.parse(m[1].trim()),nodes=Array.isArray(raw)?raw:[raw,...(raw?.['@graph']||[])];for(const n of nodes)if(typeof n?.articleBody==='string'&&n.articleBody.length>500)return n.articleBody}catch{}}const a=h.match(/<article\b[^>]*>([\s\S]*?)<\/article>/i),m=h.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i),t=htmlText(a?.[1]||m?.[1]||h);return t.length>500?t:''}catch(e){console.warn(`Fonte não recuperada ${url}:`,e.message);return ''}}
function target(s){const n=s.length;if(n>=30000)return'entre 1.800 e 2.500 palavras';if(n>=15000)return'entre 1.400 e 2.000 palavras';if(n>=8000)return'entre 1.000 e 1.600 palavras';if(n>=3500)return'entre 800 e 1.300 palavras';return'entre 600 e 1.000 palavras'}
async function generateOnce(a,model){const source=await fetchOriginalArticle(a.original_url);const available=source||`O corpo completo da fonte não pôde ser recuperado. Use somente estes dados e não invente informações.\nTítulo: ${a.title}\nResumo: ${a.summary||'(não informado)'}`;const prompt=`Você é o editor do Tech Check. Produza uma matéria jornalística completa em português brasileiro, fiel à fonte, sem clickbait e sem copiar frases. Cubra todas as informações relevantes: nomes, números, datas, especificações, contexto e declarações. Extensão desejada: ${target(source||a.summary||'')}.\n\ncontent deve ser Markdown simples, com parágrafos, ## subtítulos quando úteis e listas - quando naturais. Não use HTML. Não invente fatos. summary curto; content muito mais detalhado; why_it_matters e future_outlook somente com base na fonte, tratando futuro como cenário.\n\ncategory deve ser EXATAMENTE uma destas: ${categories.join(', ')}. Escolha uma. verification_level: single_source, salvo se a fonte for claramente comunicado oficial. Responda somente JSON.\nURL: ${a.original_url}\nTítulo coletado: ${a.title}\nResumo coletado: ${a.summary||'(não informado)'}\n\nCORPO DA FONTE:\n${available.slice(0,60000)}`;let r;try{r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':GEMINI_API_KEY},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.2,maxOutputTokens:8192,responseMimeType:'application/json',responseSchema,thinkingConfig:{thinkingLevel:'minimal'}}}),signal:AbortSignal.timeout(90000)})}catch(e){throw e}if(!r.ok){const body=await r.text();const e=Error(`Gemini ${r.status}: ${body.slice(0,1000)}`);e.status=r.status;throw e}const d=await r.json(),c=d.candidates?.[0],text=c?.content?.parts?.map(p=>p.text||'').join('').trim();if(!text)throw Error(`Gemini não retornou texto (${c?.finishReason||'sem conteúdo'}).`);return parseJsonText(text)}
async function generate(a){let last;for(const model of [...new Set([GEMINI_MODEL,GEMINI_FALLBACK_MODEL])])for(let i=1;i<=5;i++){try{return await generateOnce(a,model)}catch(e){last=e;const retry=[408,429,500,502,503,504].includes(e.status)||/UND_ERR_HEADERS_OVERFLOW|fetch failed|network|timeout/i.test(e.message);if(!retry||i===5)break;const d=Math.min(20000,2000*2**(i-1));console.warn(`Retry Gemini ${model} em ${d}ms`);await new Promise(r=>setTimeout(r,d))}}throw last||Error('Falha desconhecida no Gemini')}
function category(v){const s=String(v||'').trim();return categories.includes(s)?s:aliases.get(s)||null}
const newest=await getDraftArticles(30,'desc'),oldest=await getDraftArticles(10,'asc'),articles=[...new Map([...newest,...oldest].map(a=>[a.id,a])).values()],processed=[];
for(const a of articles){try{const r=await generate(a);if(!r.title||!r.summary||!r.content||!r.why_it_matters||!r.future_outlook||!r.category)throw Error('Gemini retornou campos obrigatórios incompletos.');const cat=category(r.category);if(!cat)throw Error(`Categoria inválida retornada pelo Gemini: ${r.category}`);await updateArticle(a.id,{title:r.title,summary:r.summary,content:r.content,why_it_matters:r.why_it_matters,future_outlook:r.future_outlook,verification_level:r.verification_level,status:'review',published_at:a.published_at||a.created_at});const c=await getCategoryByName(cat);if(!c)throw Error(`Categoria não encontrada: ${cat}`);await attachCategory(a.id,c.id);processed.push({id:a.id,title:r.title,category:cat,status:'review'})}catch(e){console.error(`Falha ${a.id}:`,e.message);processed.push({id:a.id,title:a.title,status:'error',error:e.message})}}
await writeFile('data/ai-processing-report.json',JSON.stringify({updated_at:new Date().toISOString(),model:GEMINI_MODEL,processed},null,2));const published=await getPublishedArticles(1000);await writeFile('data/latest.json',JSON.stringify({updated_at:new Date().toISOString(),count:published.length,articles:published},null,2));console.log(`Processadas ${processed.filter(x=>x.status==='review').length}; erros ${processed.filter(x=>x.status==='error').length}; feed ${published.length}.`);